# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'Connection'

  # Web app name
  webAppName: 'profile-web-app'

  # Environment name
  environmentName: 'Production'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build & Deploy
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.18.0'
      displayName: 'Install Node.js'

    - script: |
        yarn install
        yarn build
      displayName: 'npm install, build and test'

    # - task: CopyFiles@2
    #   displayName: 'Copy files'
    #   inputs:
    #     sourceFolder: 'build' 
    #     Contents: '**/*'
    #     TargetFolder: '$(Build.ArtifactStagingDirectory)'
    #     cleanTargetFolder: true

# Compress files into .7z, .tar.gz, or .zip.
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: 'build' #'$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs: 
        pathtoPublish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip

    - task: AzureWebApp@1
      displayName: 'Deploy to App Service'
      inputs:
        azureSubscription: '$(azureSubscription)'
        appName: '$(webAppName)'
        appType: 'webAppLinux'
        package: '$(System.ArtifactsDirectory)/$(Build.BuildId).zip'
        deploymentMethod: 'zipDeploy'